#! /usr/bin/python
import os
import sys
from shutil import copytree, ignore_patterns

current_dir = os.path.dirname(__file__)

# assert (current_dir / 'createProject').is_file(), 'Script should be executed in the pytorch-template directory'
assert len(sys.argv) == 2, 'Specify a name for the new project. Example: create_project MyNewProject'

target_dir = sys.argv[1]
# target_dir = current_dir / project_name

ignore = [".git", "data", "saved", "create_project", "LICENSE", ".flake8", "README.md", "__pycache__"]
copytree(current_dir, target_dir, ignore=ignore_patterns(*ignore))
print('New project initialized at `{}`'.format(os.path.abspath(target_dir)))
